### ISSUE TITLE
Translate Help 

### ISSUE THREAD

**Issue by ApoRes1337** [Alcidauk/CineLog#1]
Hello I wanted to ask if you might still need help translating the app? I would like to help you to translate these from English to German.

**Comment by Alcidauk** [comment]
Hi,

of course, I'm glad you offer to help me translating this app. 

In fact, I'm french and my english is sadly not perfect too. If you have any suggestion about existing english translations, I'd be happy to fix it.

If you installed my app from F-Droid, I'm currently completing metadata and translating it. It's the first app I publish at F-Droid, so I'll check if metadata are ok, and then german translations may be added too.

**Comment by ApoRes1337** [comment]
Yes of course i have it found in the F-Droid Preview.
If I have time afterwards I will have a look at the english strings. 

Maybe you can build a Stringlate integration for the project so the FOSS community can help you with the translation.
https://github.com/LonamiWebs/stringlate

Greetz from Germany
Christopher :)

**Comment by Alcidauk** [comment]
I worked a little bit today to release a new version of the app. I included the possibility to get Tmdb data in the language you prefer. I hope it will be a first step that will help you to easily use the app !

I took a look at Stringlate, but I don't understand what I can do to help you translating with it. I tried to process some translations with Stringlate and it worked well. 
Does Stringlate work with some other process than Pull requests with generated strings.xml files ? What do you mean with "integration" ?

Vielen dank für deine Interesse ;-)

Pierre

**Comment by ApoRes1337** [comment]
Hello, I am glad that you work so hard on your app.

Also yesterday I invested a lot of time and completed the translation for the German language to 50%.

Currently there are still two strings missing from the app itself and quite a few for the voice codes, I think I'll need another 1-2 days to complete everything. :)

**Comment by Alcidauk** [comment]
Hi, 

a huge thanks for your work ! I'll merge it asap.

I'm currently working on series review integration. If my work goes well, I'll create a tag soon with that feature. If it doesn't, I'll still create a tag to add your translations.

Pierre

**Comment by Alcidauk** [comment]
I (hope) I extracted all remaining translations from code now.

I added the prefix "_NOTTRANSLATED_" in german translations, if you'd like to translate it !

**Comment by ApoRes1337** [comment]
Hello, sorry for the late answers, I've had a lot to do with my own project the last few days. But I will immediately take care to translate the missing strings. :)

Greetings Christopher

**Comment by Alcidauk** [comment]
Hi, 

no problem, thanks for your help ! I just merged your PM. I built a new version a few days ago but I'll do a new one with these translations soon.

Pierre

**Comment by Ollo1** [comment]
Hello a couple of entries are not translated in v1.0.1 and show _NOTTRANSLATED_ as prefix. Would it be better keeping them just in English instead. Nevertheless I could help translating but have not done this before therefore would need a hint. By the way would a language seeting beside the system settings be helpful? Forcing it to english might be helpful during translation.

**Comment by ApoRes1337** [comment]
Hello @Ollo1 , I already translated the strings. However, we still have to wait for the new version to be built and redistributed. :)

**Comment by Ollo1** [comment]
Great. Thanks.

**Comment by Alcidauk** [comment]
Hi guys,

sorry for the late answer. I was working on the series part of the app. I'll publish a new version soon, which should containt the complete translations.

I will take care of next releases and avoid having a prefix, thanks !
