### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by KerstinMaur** [Alcidauk/CineLog#12]
Are you interested in a new icon? Do you have any ideas/wishes?

**Comment by Alcidauk** [comment]
Hi,

sorry for the late answer. Thank you for your proposal ! Yes, it could be a good idea. I admit I did draw the icon just to have one...

You probably have a better opinion than me concerning the icons in the app, but I think the biggest problem is that I don't have any unification with all these icons (I mean e.g. the add review, edit review, save icons).

But of course a beautiful main icon would be a great step ! I don't have special wishes, I just would like that both ideas of cinema and review are brought out with the icon.

Do you have any idea of what could be done ?

**Comment by KerstinMaur** [comment]
No problem, don't worry.

What do you think of that icon? The review part is missing but I am thinking about it.
Maybe you have some ideas?

![movies](https://user-images.githubusercontent.com/32022034/50048040-86fe9f00-00c2-11e9-98f9-b8247b74a074.png)

**Comment by KerstinMaur** [comment]
![movies_ii](https://user-images.githubusercontent.com/32022034/50307832-c26de480-0499-11e9-9029-a82c15b28775.png)

**Comment by Alcidauk** [comment]
Hi,

thanks for this great work ! The review part perfectly corresponds to what I was thinking about. A star is in my opinion the best item to use.

A remaining question is the color. Do you think that the pink I use is appropriate or not ? Should I go to a more red style ? 
Or should the icon be in the same pink ? Or maybe a red icon with this pink style is ok ?

**Comment by KerstinMaur** [comment]
I would recommend the attached colors.
[colors.zip](https://github.com/Alcidauk/CineLog/files/2708996/colors.zip)

**Comment by Alcidauk** [comment]
Hi, 

sorry for theses late answers, I do not have many time these last weeks. I did not try it yet, but will try to do that in the next days. I keep you in touch, thank you !

**Comment by KerstinMaur** [comment]
Here comes the updated icon.
[CineLog.zip](https://github.com/Alcidauk/CineLog/files/2793327/CineLog.zip)

**Comment by KerstinMaur** [comment]
The new version looks great, I like it! 😎
