### ISSUE TITLE
Titles of all saved series replaced by most recent

### ISSUE THREAD

**Issue by ghost** [Alcidauk/CineLog#14]
New to GitHub so I apologize in advance if this isn't the right place. I'm using an LG G3 with CyanogenMod 13.0 (Android 6.0.1).

The movie portion of the app is working fine for me, but in the Series tab, the name of every series is replaced by the name of the series I added most recently. This screenshot was taken right after I added Bojack Horseman to the list. I added The Office next and every entry changed to The Office.

![screenshot_20181228-201853](https://user-images.githubusercontent.com/4174610/50531875-d095b380-0ade-11e9-87ca-c8634f4486c5.png)

Unrelated, but while I'm here, it'd be nice to add a movie/series to the list without giving it a rating. i.e. mark it as "watched" but not yet reviewed. As of now, I'm just giving them all 0.5/10 until I come back and review them later.

**Comment by Alcidauk** [comment]
Hi,

It is the right place, thank you !

I'll take a look at the issue soon. It should not be difficult to fix it. I keep you up to date.

And thanks too for your suggestion. You are right, there is no good reason to force to fill the rating when creating a review. I'll try to avoid this.

Pierre

**Comment by Alcidauk** [comment]
Hi,

I just fixed the bug you were reporting. It was a major issue, and it was, when you add a new serie review, erasing all the previous ones, and also the serie title.

Fortunately, as I understand your current use of the app, you were not saving review but only the fact that you saw series. So it shouldn't have an effect on your list.

My remaining work is to add a small work at the next launch of the app to fix existing serie reviews people have in their app. I'll try to do it asap and will then publish a new version of the app.

Thanks again for your review,

Pierre.
