### ISSUE TITLE
Export in app sub folder

### ISSUE THREAD

**Issue by Buxdehuda** [Alcidauk/CineLog#19]
Currently the export files are saved in the main directory. A separate folder should be created for this.

**Comment by Alcidauk** [comment]
Hi,

you're right, I'll fix that soon. For your information, if you enable automatic save, it is already done in a specific directory. Thanks for your report.

**Comment by Alcidauk** [comment]
Hi,

the next release will now export and import in a CineLog directory and not in the root dir anymore.

I close this issue. Please notice me if you find any bug on this feature !
