### ISSUE TITLE
no import / export whishlist 

### ISSUE THREAD

**Issue by mart1oeil** [Alcidauk/CineLog#22]
Hi,

I have done an export. After I uninstalled and reinstalled the app and imported the file. Noted movies are well exported but the wishlist is not. :/

**Comment by Alcidauk** [comment]
Hi,

yes, it is a missing feature, that's why I disabled import/export item in the wishlist menu. 

But you are right, it is a major lack of the app currently. I planned to implement it ASAP.

Thank you for your report,

Pierre

**Comment by Alcidauk** [comment]
Hi,

better late than never... I finally implemented this feature. It should be deployed in a new release soon !

Pierre
