### ISSUE TITLE
Suggestion: Setting to change default sort order

### ISSUE THREAD

**Issue by udidengu82** [Alcidauk/CineLog#26]
Currently whenever I start the app the movies are sorted from first added to last added.
I would like the abilty to change this to any of the other sort orders, preferably I would like to have the default view set to sort by release year (newest first).

**Comment by Alcidauk** [comment]
Hi,

could be easily done. I'll try to spend a little moment on it in the next features.

Thank you for your suggestion !

**Comment by Alcidauk** [comment]
Hello,

took a (very) long time, but your suggestion is now implemented ! You will be able to use it in the next version (1.3.3).

Pierre
