### ISSUE TITLE
Android 10 storage permission

### ISSUE THREAD

**Issue by yekteniya** [Alcidauk/CineLog#30]
I'm using Android 10 and I'm having issues importing and exporting even though I have storage permission enabled. 

I believe this might have to do with Android 10 changing the way it handles storage permissions (scoped storage), but don't quote me on that.

**Comment by amadeous** [comment]
I am also experiencing importing issues. I upgraded from Android 8 to 10 and exported at the beginning four files (export_series, export_movies, export_wishlist_series, export_wishlist_movies) but cannot import them back now.

After renaming the exported file (replacing 'export' by 'import') and trying to import them, I have an error message asking me to make sure the file are there and to check that the app has the permission to access them. Could you do something about it?

Thank for the fork you made and your time to keep this a very useful app!

**Comment by Alcidauk** [comment]
Hi,

I just pushed a new version with a bugfix for android X version. Tell me if it changes the IO features behaviour !

Pierre

**Comment by nathanpuch** [comment]
Hi,
It works as expected on Android 10 now!

**Comment by yekteniya** [comment]
With the new version I have been able to import 300+ ratings from my Filmaffinity account without any issues. Thanks for the effort!

**Comment by amadeous** [comment]
Also worked for me, thanks!

**Comment by Go-rom** [comment]
Hello, is anyone getting the same issue with android 11? 

Thank you
