### ISSUE TITLE
Dark theme unreadable dialog

### ISSUE THREAD

**Issue by yekteniya** [Alcidauk/CineLog#31]
Long press over an item in the review/wishlist section while using dark theme, will show a dialog with an unreadable text giving cancel or yes options.

![Screenshot_20200531-144452_CineLog](https://user-images.githubusercontent.com/52610846/83352856-d84e2d00-a34e-11ea-9043-bd8b6d58bc6a.png)

**Comment by Alcidauk** [comment]
Hi,

I've been working on this in the past months, but I did not ended the fix. I'll try to fix it soon.

Thank you for the bug report,

Pierre

**Comment by Alcidauk** [comment]
Hi,

I just fixed this issue, and some other app's parts that were not taken in account in dark theme.

It should be published soon ;-)

Pierre

**Comment by murlakatamenka** [comment]
Not fixed in the wishlist.

**Comment by Alcidauk** [comment]
Fixed after theme rewrite.

**Comment by murlakatamenka** [comment]
Thanks!
