### ISSUE TITLE
Crash issue 

### ISSUE THREAD

**Issue by YYYSSSHHH** [Alcidauk/CineLog#32]
**Environment Info：**
APK version 1.3.1 (27) 
AndroidOS Version = “6.0.1”

**Reproduce step:**
One: Enter a  movie titles.
Two: quickly click 2 .
![1](https://user-images.githubusercontent.com/55122523/90482374-bc943f00-e165-11ea-8d79-a45b8a3fdca6.png)
When I input  "hannibal"   and  click 2 quickly, the app will crash directly.

**Finally:**
If you have confirmed or fixed this problem, please give me a reply, thank you!

**Comment by Alcidauk** [comment]
Hi,

I will try to reproduce it in the next few days. I will let you know the result as soon as possible. Thank you for your report !

Pierre

**Comment by Alcidauk** [comment]
Hi,

I do not reproduce your issue. Could you provide some other clues ?

Does this issue happen for every text you type ?

Pierre
