### ISSUE TITLE
Adding films doesn't work on Android 4.4.4

### ISSUE THREAD

**Issue by miky-kr5** [Alcidauk/CineLog#33]
Hello.

I just installed CineLog and when using the app (installed from F-Droid) I have an error in the view that allows searching for movies in TmDB in a Galaxy Tab 2 7" (espressowifi) using a SlimKat Android 4.4.4 rom. After I type the film name the circle indicator starts spinning but after the search is done there is no movie list to choose from. I also tried it in an Asus ZenFone 2 with the standard Asus rom (Android 5 Lemon Pie with ZenUI) and it works perfectly there.

If there is anything I can do to help  fix this of if you would need more information please tell me.

Best regards.

**Comment by Alcidauk** [comment]
Hi,

I'll try to reproduce it with a Kitkat emulator. I keep you up to date,

Thanks for the feedback,

Pierre

**Comment by Alcidauk** [comment]
Android KitKat is not supported anymore. It was too difficult to keep that, I sadly have not enough time.
