### ISSUE TITLE
Allow multiple viewings/reviews per movie [Feature Request]

### ISSUE THREAD

**Issue by aguerny** [Alcidauk/CineLog#39]
Anything in the works to allow multiple reviews per movie? If I re-watch a film in the future, I'd like to see separate entries (viewing dates, ratings, comments) for each separate time I mark a movie as watched. Currently I can only edit my previous viewing entry. Thanks!

**Comment by Alcidauk** [comment]
Hi,

Someone else asked a feature that is like yours (https://github.com/Alcidauk/CineLog/issues/66). I close this one because I put some more details on the other one.

Thanks,

Pierre.
