### ISSUE TITLE
auto backup of wishlists

### ISSUE THREAD

**Issue by JocelynDelalande** [Alcidauk/CineLog#40]
movies/series view logs are backed up after opt-in in settings.

Those backups can then be imported in cinelog. That is great.

But surprisingly, only watch logs are backed up up that way, not wishlists, any reason to that ?

(no drama but for the record, I lost my wishlists that way)

PS: and a big thanks for that app <3.

**Comment by Alcidauk** [comment]
Hi,

I worked on I/O features in the previous release, and this issue should be fixed. Could you please try it again ?

Thanks !

Pierre
