### ISSUE TITLE
Tagging and searching features for films' and series' lists

### ISSUE THREAD

**Issue by belgiumed** [Alcidauk/CineLog#44]
Hello Pierre,

I was wondering if you consider developing a tagging feature to films' and series' lists and adding a search field ? This way one could make customized lists and easily search through relatively long lists :-)

Thanks again for the time you spend forking this awesome app :)
Belgiumed

**Comment by Alcidauk** [comment]
Hi,

I just released a new version with a tagging feature. For now, you're not able to filter list depending on tag, but I'll try to implement this in the next release !

Thanks for using the app ;-)

Pierre

**Comment by belgiumed** [comment]
Hi Pierre, 

Thank you very much for the update and for making this kind of app available to everybody ! I'm looking forward to the next release :)

Belgiumed
