### ISSUE TITLE
fr typo error in import page

### ISSUE THREAD

**Issue by Saimyx** [Alcidauk/CineLog#45]
There is an error in the text (in french) : 
- "Import de la liste de souhaits de films:"
- "Import de la liste de souhaits des films:"

There are 2 "films" and there are not "series"

You can see it in screenshot (V1.3.3) :
![Screenshot_20220220-153833_CineLog](https://user-images.githubusercontent.com/44293594/154848303-72c56371-76d2-4ed2-90e5-2dfa1fb1a3ad.jpg)

**Comment by Alcidauk** [comment]
Hello,

thank you for your report. I just fixed it, and it should be available when I'll package the next release.

Pierre
