### ISSUE TITLE
error in import wishlists

### ISSUE THREAD

**Issue by Saimyx** [Alcidauk/CineLog#46]
When I had imported my 4 files there is an error : my movies wishlist was not imported but these was imported in section series wishlist.

When I had renamed the file from "export_wishlist_movies.csv" to "export_wishlist_series.csv" my movies was correctly imported in the good section.

V1.3.3

PS : I love this app <3 thank you for the very good job !

**Comment by Alcidauk** [comment]
Hi,

You're right, there was a problem. Should be fixed in 4.0.1 ;-)
