### ISSUE TITLE
Slow performance on list screen

### ISSUE THREAD

**Issue by TroyDowling** [Alcidauk/CineLog#47]
Scrolling the list of entries in the main screen is slow; stuttering at about 1 FPS, the list jumps along more than it smoothly scrolls. It also takes about one second to go back to the main list from viewing a review record. In my case, I only have about 30 entries in total. Performance everywhere else seems fine. I use a OnePlus 3T device on LineageOS 18.1 / Android 11.

Maybe there's some crust in how the program is drawing the list? Or, considering I didn't see any other issues like this on the board, maybe it's just me?

Thanks.

**Comment by yekteniya** [comment]
I can confirm I have this issue too, using Lineage both in Android 11 and Android 12. Thought this was due to having almost 500 entries but the fact that this already is happening as you say at 30~ entries is not ideal.

**Comment by Alcidauk** [comment]
Hi guys,

I just published a new version that fix these performances issues. You should now have a much better experience.

Thanks for reporting !

Pierre

**Comment by yekteniya** [comment]
Update just came in through F-Droid and the improvement is very noticeable. Scrolling now works as expected even despite having hundreds of reviews. Great work!

**Comment by TroyDowling** [comment]
Thanks for the heads up @yekteniya, I was waiting for the same. And a big thanks to @Alcidauk since I can confirm this was the fix for me as well!
