### ISSUE TITLE
Settings panel is completely black

### ISSUE THREAD

**Issue by opk12** [Alcidauk/CineLog#50]
Open the app, tap the hamburger menu, click `Settings`. The window is completely black, with the white lines at the top

    General preferences
    Set the global preferences of this app.

![d](https://user-images.githubusercontent.com/40740650/189606957-2e837936-cefd-4323-bc45-34b9375447fd.png)

**Comment by Alcidauk** [comment]
Hi,

I just fixed it. It should be ok in a next release. I let you close the ticket when you will get this !

Pierre

**Comment by opk12** [comment]
Solved, thanks!
