### ISSUE TITLE
Tags added randomly to films

### ISSUE THREAD

**Issue by belgiumed** [Alcidauk/CineLog#55]
Hi Pierre,

Thanks for adding a tag features !
I have come across a weird behavior when adding tag : it is added to some others films without any action from me. I've created a tag "Quentin Dupieux" and added to "Deerskin/Le daim" and the dot related to this tag appears in the list above the rating stars of some other films like "Escape from LA", "Hell or High Water", "Joker", etc. Whenever I click on those films, that tag field is empty though. In some case, the dot appear twice for the same movie (for instance the dot related to the tag "Documentary" on one of the "Indiana Jones" movies, although I sure it can be considered as a documentary by some people ;-)

Have a nice day
Belgiumed

**Comment by Alcidauk** [comment]
Hi Belgiumed,

Thanks for this detailed scenario. I reproduced your issue and fixed it, in the next release. This will be a beta release since I refactored a lot of code. Don't hesitate to create issues if you catch some !

Pierre
