### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Alcidauk/CineLog#57]
https://monitor.f-droid.org/builds/log/com.ulicae.cinelog/36#site-footer

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/vagrant/build/com.ulicae.cinelog/app/build/intermediates/incremental/release/mergeReleaseResources/stripped.dir/layout/nav_header.xml:14: AAPT: error: resource drawable/icon (aka com.ulicae.cinelog:drawable/icon) not found.
```

Could you please take a look? Thanks!

**Comment by linsui** [comment]
By the way, I'm going to remove the summaries from fdroiddata repo in favour the fastlane data in your repo. You can add them to your repo. See https://gitlab.com/fdroid/fdroiddata/-/tree/4d9cf75a82358285397f6932d7ca457ee1b2c025/metadata/com.ulicae.cinelog

**Comment by Alcidauk** [comment]
Hi,

Yes I will take a look in the next few days.

Thanks for the summaries, I was aware that I should change something but did not take the time. I'll add it !

**Comment by Alcidauk** [comment]
I just fixed this issue. Tell me if build is now processing successfully.

**Comment by linsui** [comment]
It's fixed. Thanks!
