### ISSUE TITLE
Add dark theme (Suggestion)

### ISSUE THREAD

**Issue by Ollo1** [Alcidauk/CineLog#6]
It would be great to have a dark theme for the app.

Thanks for this nice app.

**Comment by Alcidauk** [comment]
Good idea, I'll try to see if it costs a lot of time, but I don't think so. I'll give you informations about it as soon as possible.

Thank you !

**Comment by Alcidauk** [comment]
Included in the last release (1.1). If you have any suggestion to improve the dark theme, I let you open a new issue.
