### ISSUE TITLE
[BUG] Cannot select a tag for the movie

### ISSUE THREAD

**Issue by sidongfeng** [Alcidauk/CineLog#60]
To reproduce:
1. Tap on the "films" tab at the navigation bar
2. Click add a review
3. Enter a movie name, i.e., "Dragon Ball"
4. Click "Dragon Ball" and click the "+" icon at the bottom
5. Press on "EDIT TAGS"

It should allow me to edit tags of the films, but no tags available.

**Comment by Alcidauk** [comment]
Hi,

This is not a bug, but you're right, it's a little bit confusing. 

You need to enable tags first for movies and/or for series to use them.

I just added a message when no tag are shown to explain this. It should be available in the next version.
