### ISSUE TITLE
[suggestion] Releasing the apk here on Github

### ISSUE THREAD

**Issue by EdoSecco** [Alcidauk/CineLog#62]
I use [Obtainium](https://github.com/ImranR98/Obtainium) and it would be great if you publish the apk in the release section.

Thank you!

**Comment by Alcidauk** [comment]
Hello EdoSecco,

For practical reasons, I don't build app myself, but completely delegate it to F-droid.

However, I can get their built APK and add it here to allow you to download it using Obtainium.

I'll try this with the next version :-)

Pierre.

**Comment by Alcidauk** [comment]
Hi,

Due to the use of greendao, fdroid maintainers have disable cinelog updates.

I remembered this issue, and I just fixed it. You should find a first release, the 2.0.0 version.

Thank you,

Pierre
