### ISSUE TITLE
Wrong item when opening or deleting a filtered item from the wishlist

### ISSUE THREAD

**Issue by sbssk8** [Alcidauk/CineLog#63]
Opening a movie or series after filtering opens the element on the position of the list as if no filter was applied.

![cinelog_filter_wishlist_bug](https://github.com/Alcidauk/CineLog/assets/1192193/8baefe7a-ba57-4077-b506-ff4112b1f354)

**Comment by Alcidauk** [comment]
Hi, 

Sorry for the late answer, and thanks for your fix, I'll include it in the next version :-)

Pierre
