### ISSUE TITLE
greendao gradle plugin is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [Alcidauk/CineLog#76]
ref: https://github.com/greenrobot/greenDAO/issues/412

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6464200025#L271

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d03c57fdbd836fff73375503227fca3acdbf32e5

**Comment by Alcidauk** [comment]
Hi licaon-kter,

Thank you for your report, I wasn't aware of this matter. 

Unfortunately, GreenDao was introduced before Kinolog fork, and this project is closely joined to this librairy.

I will try to migration to another solution, but can't give you an ETA.

Have a nice day,

Pierre

**Comment by licaon-kter** [comment]
Can you drop the plugin and include the generated part, eg: https://github.com/wallabag/android-app/pull/1406

**Comment by Alcidauk** [comment]
Hi,

I did not thought to get the generated part, and I took advantage of this issue to rewrite the app DAO part. I'm currently working on it, and it should be available in the next few weeks.

**Comment by licaon-kter** [comment]
Yes, replacing it completely would be nicer

**Comment by linsui** [comment]
The source code of the plugin is published.
