### ISSUE TITLE
Sort by title

### ISSUE THREAD

**Issue by Ollo1** [Alcidauk/CineLog#9]
Beside rating, release year, view date sorting by title would be great. I thought it was in v1.0 but at least it is no longer in v1.0.1.

**Comment by Alcidauk** [comment]
Hi,

it wasn't in v1.0, but you are right, it would be great. I will add it. Thank you for this report.

**Comment by Alcidauk** [comment]
Added for movies in the 1.1 release. Will be added too for series asap.
